  - name: task1..installing mysql
    ansible.builtin.package:
      name: "mysql-server"
      state: present

  - name: task2..enabling and starting the service
    ansible.builtin.service:
      name: mysqld
      enabled: true
      state: started    

  - name: task3..setup root password
    vars_promopt:
      - name: ROOT_PASSWORD
        prompt: Enter root password
    ansible.builtin.command: 'mysql_secure_installation --set-root-pass {{ ROOT_PASSWORD }}'    